### ISSUE TITLE
[Java-MOOCTextEditor] Tests passed but the Grader didn't

### ISSUE THREAD

**Issue by JiYangE** [JiYangE/Prac-Py-Jav#1]
After changing some logical mistake in the if statements for exception throws, now we can pass all the test we already have. But during the running of the Grader program, there is such error info:

    Exception in thread "main" java.lang.IndexOutOfBoundsException: Index out of range!
	at textgen.MyLinkedList.getNode(MyLinkedList.java:72)
	at textgen.MyLinkedList.add(MyLinkedList.java:94)
	at textgen.MyLinkedListGrader.doTest(MyLinkedListGrader.java:89)
	at textgen.MyLinkedListGrader.main(MyLinkedListGrader.java:107)

**Comment by JiYangE** [comment]
[Solved. Click for the corresponding commit.](https://github.com/JiYangE/Prac-Py-Jav/commit/2b9d9a41c605422ff387aecc71eedf52d0da7774)
